package ma.emsi.gare.enums;

public enum TypeNotification {
    RETARD,
    ANNULATION,
    CHANGEMENT_QUAI,
    CONFIRMATION_RESERVATION,
    RAPPEL_DEPART,
    TRAJET_DEMARRE,
    TRAJET_TERMINE,
    INCIDENT,
    ALERTE_GARE,
    JALON_ARRIVEE,
    JALON_DEPART,
    TICKET_VALIDE
}