sonar.projectKey=layhirayan_testsonar

sonar.sources=.

sonar.token=0c16d1c8ad800e6497487c436cf8b65a1d336aaa

sonar.sourceEncoding=UTF-8

sonar.java.binaries=target

sonar.host.url=https://sonarcloud.io

sonar.organization=layhirayan